modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="brokenmirror"
version="1.0.0"
displayName="Broken Mirror"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="brokenmirror.png"
credits="Some of the used scripts where written by Choonster." #optional
authors="Clocken"
description='''Implements a new recipe type for creating fixed (non-mirrored) shaped recipes.'''# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

[[dependencies.brokenmirror]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.brokenmirror]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
